### ISSUE TITLE
Consumed new food items don't affect Saturation

### ISSUE THREAD

**Issue by EasyMFnE** [KyleMMoore/FoodStuffEx_Issue-Tracker#2]
Consuming added food items (tested baked carrot, simmered melon, baked apple so far) increases food/hunger meter but does not increase saturation.
(See https://minecraft.gamepedia.com/Hunger#Saturation for basic information on Saturation)

Tested using Macro Mod to see actual player saturation number/value, and confirmed to not just be a client-side discrepancy by monitoring rate at which health is restored after eating.

**Comment by KyleMMoore** [comment]
Looking into this.

**Comment by KyleMMoore** [comment]
Issue resolved.
